---
- hosts: controlplanes
  become: yes
  become_method: sudo
  tasks:
    - name: "Enable kubelet"
      shell: systemctl enable kubelet
    - name: "kubeadm pull"
      shell: "kubeadm config images pull"
- hosts: controlplane-1
  become: yes
  become_method: sudo
  tasks:
    - name: kubeadm init
      shell: "kubeadm init --control-plane-endpoint \"172.25.4.1\" --pod-network-cidr \"10.244.0.0/16\" --upload-certs"
    - name: get control plane cert
      shell: "kubeadm init phase upload-certs --upload-certs | tail -n 1"
      register: control_plane_cert
    - name: Create token w/ infinite TTL
      shell: kubeadm token create --ttl 0 --print-join-command
      register: join_command
    - name: save tokens
      add_host:
        name:   "K8S_TOKEN_HOLDER"
        token:  "{{ join_command.stdout }}"
        hash:   "{{ control_plane_cert.stdout }}"
    - name: copy kubeconfig
      shell: mkdir -p /root/.kube && cp /etc/kubernetes/admin.conf /root/.kube/config
    - name: download kubectl
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /tmp/kubeconfig
    - name: install calico
      shell: | 
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/tigera-operator.yaml
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/custom-resources.yaml
    - name: copy metallb conf
      copy:
        src: ./metallb-conf.yml
        dest: /tmp/metallb-conf.yml
    - name: install metallb
      shell: | 
        kubectl get configmap kube-proxy -n kube-system -o yaml | \
          sed -e "s/strictARP: false/strictARP: true/" | \
          kubectl apply -f - -n kube-system

        kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yaml
        kubectl apply -f /tmp/metallb-conf.yml
- hosts: controlplane-others
  become: yes
  become_method: sudo
  tasks:
    - name: run kubeadm join
      shell: "{{ hostvars['K8S_TOKEN_HOLDER']['token'] }} --control-plane --certificate-key {{ hostvars['K8S_TOKEN_HOLDER']['hash'] }}"
    - name: save join command
      local_action: copy content="{{ hostvars['K8S_TOKEN_HOLDER']['token'] }}" dest=./.join_command